# Generated by Django 5.0.4 on 2024-04-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(default='DEFAULT VALUE', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=128)),
                ('clave', models.CharField(default='DEFAULT VALUE', max_length=128)),
                ('correo', models.CharField(default='DEFAULT VALUE', max_length=128)),
            ],
        ),
    ]
