# Generated by Django 5.0.4 on 2024-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas_app', '0002_store_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='id_store',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
