# Generated by Django 5.0.4 on 2024-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas_app', '0003_remove_store_id_alter_store_id_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
